// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	user "github.com/dalikewara/ayapingping-go/src/domains/user"
	mock "github.com/stretchr/testify/mock"
)

// UseCaseInterface is an autogenerated mock type for the UseCaseInterface type
type UseCaseInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: param
func (_m *UseCaseInterface) Create(param user.UseCaseCreateParam) user.UseCaseCreateResult {
	ret := _m.Called(param)

	var r0 user.UseCaseCreateResult
	if rf, ok := ret.Get(0).(func(user.UseCaseCreateParam) user.UseCaseCreateResult); ok {
		r0 = rf(param)
	} else {
		r0 = ret.Get(0).(user.UseCaseCreateResult)
	}

	return r0
}

// GetAll provides a mock function with given fields: param
func (_m *UseCaseInterface) GetAll(param user.UseCaseGetAllParam) user.UseCaseGetAllResult {
	ret := _m.Called(param)

	var r0 user.UseCaseGetAllResult
	if rf, ok := ret.Get(0).(func(user.UseCaseGetAllParam) user.UseCaseGetAllResult); ok {
		r0 = rf(param)
	} else {
		r0 = ret.Get(0).(user.UseCaseGetAllResult)
	}

	return r0
}
