// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	service "github.com/dalikewara/ayapingping-go/v2/src/service"
	mock "github.com/stretchr/testify/mock"
)

// Example is an autogenerated mock type for the Example type
type Example struct {
	mock.Mock
}

// GetAll provides a mock function with given fields: param
func (_m *Example) GetAll(param service.ExampleGetAllParam) service.ExampleGetAllResult {
	ret := _m.Called(param)

	var r0 service.ExampleGetAllResult
	if rf, ok := ret.Get(0).(func(service.ExampleGetAllParam) service.ExampleGetAllResult); ok {
		r0 = rf(param)
	} else {
		r0 = ret.Get(0).(service.ExampleGetAllResult)
	}

	return r0
}

type mockConstructorTestingTNewExample interface {
	mock.TestingT
	Cleanup(func())
}

// NewExample creates a new instance of Example. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewExample(t mockConstructorTestingTNewExample) *Example {
	mock := &Example{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
