// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	service "github.com/dalikewara/ayapingping-go/src/service"
	mock "github.com/stretchr/testify/mock"
)

// User is an autogenerated mock type for the User type
type User struct {
	mock.Mock
}

// GetAll provides a mock function with given fields: param
func (_m *User) GetAll(param service.UserGetAllParam) service.UserGetAllResult {
	ret := _m.Called(param)

	var r0 service.UserGetAllResult
	if rf, ok := ret.Get(0).(func(service.UserGetAllParam) service.UserGetAllResult); ok {
		r0 = rf(param)
	} else {
		r0 = ret.Get(0).(service.UserGetAllResult)
	}

	return r0
}

type mockConstructorTestingTNewUser interface {
	mock.TestingT
	Cleanup(func())
}

// NewUser creates a new instance of User. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUser(t mockConstructorTestingTNewUser) *User {
	mock := &User{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
