// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	example "github.com/dalikewara/ayapingping-go/src/domains/example"
	mock "github.com/stretchr/testify/mock"
)

// RepositoryInterface is an autogenerated mock type for the RepositoryInterface type
type RepositoryInterface struct {
	mock.Mock
}

// FindById provides a mock function with given fields: param
func (_m *RepositoryInterface) FindById(param example.RepositoryFindByIdParam) example.RepositoryFindByIdResult {
	ret := _m.Called(param)

	var r0 example.RepositoryFindByIdResult
	if rf, ok := ret.Get(0).(func(example.RepositoryFindByIdParam) example.RepositoryFindByIdResult); ok {
		r0 = rf(param)
	} else {
		r0 = ret.Get(0).(example.RepositoryFindByIdResult)
	}

	return r0
}

// UpdateNameById provides a mock function with given fields: param
func (_m *RepositoryInterface) UpdateNameById(param example.RepositoryUpdateNameByIdParam) example.RepositoryUpdateNameByIdResult {
	ret := _m.Called(param)

	var r0 example.RepositoryUpdateNameByIdResult
	if rf, ok := ret.Get(0).(func(example.RepositoryUpdateNameByIdParam) example.RepositoryUpdateNameByIdResult); ok {
		r0 = rf(param)
	} else {
		r0 = ret.Get(0).(example.RepositoryUpdateNameByIdResult)
	}

	return r0
}
