// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	example "github.com/dalikewara/ayapingping-go/src/domains/example"
	mock "github.com/stretchr/testify/mock"
)

// UseCaseInterface is an autogenerated mock type for the UseCaseInterface type
type UseCaseInterface struct {
	mock.Mock
}

// GetAndChangeName provides a mock function with given fields: param
func (_m *UseCaseInterface) GetAndChangeName(param example.UseCaseGetAndChangeNameParam) example.UseCaseGetAndChangeNameResult {
	ret := _m.Called(param)

	var r0 example.UseCaseGetAndChangeNameResult
	if rf, ok := ret.Get(0).(func(example.UseCaseGetAndChangeNameParam) example.UseCaseGetAndChangeNameResult); ok {
		r0 = rf(param)
	} else {
		r0 = ret.Get(0).(example.UseCaseGetAndChangeNameResult)
	}

	return r0
}
