// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	repository "github.com/dalikewara/ayapingping-go/src/repository"
	mock "github.com/stretchr/testify/mock"
)

// Role is an autogenerated mock type for the Role type
type Role struct {
	mock.Mock
}

// FindByUserID provides a mock function with given fields: param
func (_m *Role) FindByUserID(param repository.RoleFindByUserIDParam) repository.RoleFindByUserIDResult {
	ret := _m.Called(param)

	var r0 repository.RoleFindByUserIDResult
	if rf, ok := ret.Get(0).(func(repository.RoleFindByUserIDParam) repository.RoleFindByUserIDResult); ok {
		r0 = rf(param)
	} else {
		r0 = ret.Get(0).(repository.RoleFindByUserIDResult)
	}

	return r0
}

type mockConstructorTestingTNewRole interface {
	mock.TestingT
	Cleanup(func())
}

// NewRole creates a new instance of Role. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRole(t mockConstructorTestingTNewRole) *Role {
	mock := &Role{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
